export const ADD_BOX = "ADD_BOX";
export const FETCH_BOXES = "FETCH_BOXES";
export const FETCH_BOXES_SUCCESS = "FETCH_BOXES_SUCCESS";
export const ADD_BOX_SUCCESS = "ADD_BOX_SUCCESS";
export const FETCH_COUNTRIES_SUCCESS = "FETCH_COUNTRIES_SUCCESS";
